
services:

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile  
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - llm_api_key=${llm_api_key}
      - DOCKER_ENV=true
      - DOCKER_REDIS_URL=${DOCKER_REDIS_URL}
    volumes:
      - .:/app  
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "2"]
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000 
    volumes:
      - ./frontend:/app
    command: ["npm", "start"]
    restart: always
